- name: Install rsyslog server config files
  block:
    - name: Deploy rsyslog.conf on server
      copy:
        src: rsyslog.conf_ubuntu.client
        dest: /etc/rsyslog.conf
        owner: root
        group: root
        mode: '0644'

    - name: Deploy rsyslog rules on client
      copy:
        src: rsyslog.rule_client
        dest: /etc/rsyslog.d/60_remotelog.conf
        owner: root
        group: root
        mode: '0644'
  notify: Restart rsyslog
